'use client'
import { useEffect, useState, Suspense } from "react";
import { AppCard } from "@/components/app-card"; // we'll make this
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { toast } from "sonner";
import { useRouter, useSearchParams } from "next/navigation";
import { error } from "console";
import { Pie } from "@visx/shape";
import dynamic from 'next/dynamic';

// Dynamic import with SSR disabled
const VisxPieChart = dynamic(() => import('@/components/pie-Chart'), {
  ssr: false,
});





interface AppData {
  _id?: string;
  userId: string;
  subscriptionId: string;
  resourceGroup: string;
  appServiceName: string;

  name: string;
  budget: number;
  AppName?: string;

  cost?: number;
  autoStop?: boolean;
  lastSynced?: string; 

  isDraft?: boolean;
  createdAt?: string; 
  updatedAt?: string; 
}
interface ResourceGroup {
  _id?: string; // Optional, since it’s generated by MongoDB
  userId: string;
  subscriptionId: string;
  name: string;
  location?: string;
  budget: number;
  cost: number;
  autoStop: boolean;
  createdAt?: string;
  updatedAt?: string;
}



function DashboardContent() {
  const [apps, setApps] = useState<AppData[] | []>([]);
  const [resourceGroups,setresourceGroups]=useState<ResourceGroup[] | []>([])
  const [loading, setLoading] = useState(true);
  const [linked, setLinked] = useState(false);
  const searchParams = useSearchParams();
  const router = useRouter();

  useEffect(() => {
    const linked = searchParams.get('linked')
    if (linked == 'true') {
      toast("Your account has been successfully linked", {
        description: "Now you can deploy your apps to Azure",
      })
      setLinked(true);
      const params = new URLSearchParams(window.location.search);
      params.delete("linked");
      const newUrl = window.location.pathname + (params.toString() ? `?${params}` : "");
      router.replace(newUrl);
    }
  },[])

  const handleSync=async ()=>{
    setLoading(true);
    try {
      const res = await fetch('/api/auth/azure/sync', { method: 'POST' });
      const data = await res.json();
      
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Failed to sync with Azure');
      }
      
      toast.success('Successfully synced with Azure!');
      
      // Refresh the page to show new data
      window.location.reload();
    } catch (error: any) {
      console.error(error);
      toast.error(error.message || 'Error syncing with Azure');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    fetch("/api/apps")
      .then(res => res.json())
      .then(data => {
        setApps(data.data || []);
        
      });

      fetch("/api/resourceGroup")
      .then(res=>res.json())
      .then(data=>setresourceGroups(data.data || []))
      .finally(()=>setLoading(false))
      
  }, []);

  if (loading) return <p className="p-4">Loading apps...</p>;

  // Group apps by resourceGroup
  const appsByGroup: { [key: string]: AppData[] } = apps.reduce((acc, app) => {
    if (!acc[app.resourceGroup]) acc[app.resourceGroup] = [];
    acc[app.resourceGroup].push(app);
    return acc;
  }, {} as { [key: string]: AppData[] });

  // Calculate aggregated budget and cost per Resource Group
  const rgCoins = Object.entries(appsByGroup).map(([group, groupApps]) => {
    const totalBudget = groupApps.reduce((sum, app) => sum + (app.budget || 0), 0);
    const totalCost = groupApps.reduce((sum, app) => sum + (app.cost || 0), 0);
    return {
      name: group,
      budget: totalBudget,
      cost: totalCost
    };
  }).filter(rg => rg.budget > 0);

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-semibold">Your Apps</h1>
        <Link href="/dashboard/createApp">
          <Button>Create New App</Button>
        </Link>
        <Link href="/resourceGroup">
          <Button variant="outline">Create Resource Group</Button>
        </Link>
        {!linked && (
          <div className="flex gap-2">
            <Button onClick={() => window.location.href = "/api/auth/azure"}>
              Connect Azure Account
            </Button>
            <Button variant="outline" onClick={() => {
              const tenantId = prompt(
                "Enter your Azure Tenant ID:\n\n" +
                "Use this if the normal login doesn't recognize your email.\n" +
                "Find it in Azure Portal → search 'Tenant properties' → Tenant ID"
              );
              if (tenantId && tenantId.trim()) {
                window.location.href = `/api/auth/azure?tenantId=${tenantId.trim()}`;
              }
            }}>
              Use Tenant ID
            </Button>
          </div>
        )}
        <Button onClick={handleSync}>Get Subs</Button>
      </div>
      <div className="flex">
        <VisxPieChart
          coins={rgCoins as any}
        />
        <div className="flex-1 space-y-8">
          {Object.entries(appsByGroup).map(([group, groupApps]) => {
            const rgData = resourceGroups.find(rg => rg.name === group) as any;
            const isDeleting = rgData?.status === "Deleting";

            return (
              <div key={group} className={`border rounded-lg p-4 shadow-sm ${isDeleting ? "opacity-60 bg-gray-50 pointer-events-none grayscale" : ""}`}>
                <div className="flex items-center gap-3 mb-3">
                  {isDeleting ? (
                    <h2 className="text-xl font-bold text-gray-500">
                      {group}
                    </h2>
                  ) : (
                    <Link href={`/resourceGroup/${group}`}>
                      <h2 className="text-xl font-bold text-blue-600 hover:underline cursor-pointer">
                        {group}
                      </h2>
                    </Link>
                  )}
                  {isDeleting && (
                    <span className="flex items-center gap-1 text-xs font-medium bg-red-100 text-red-700 px-2.5 py-0.5 rounded-full animate-pulse border border-red-200 shadow-sm">
                      <svg className="w-3 h-3 animate-spin" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Deleting from Azure...
                    </span>
                  )}
                </div>
              <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
                {groupApps.map(app => {
                  const appLink = app.AppName
                    ? `/dashboard/monitor/${app._id}`
                    : app.isDraft
                      ? `/dashboard/deploy/${app._id}`
                      : `/dashboard/deploy/${app._id}/prepare`;
                  return (
                    <Link href={appLink} key={app._id}>
                      <AppCard app={app} />
                    </Link>
                  );
                })}
              </div>
            </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

export default function Dashboard() {
  return (
    <Suspense fallback={<div>Loading dashboard...</div>}>
      <DashboardContent />
    </Suspense>
  );
}

